GET http://127.0.0.1:10001/movies/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJ1c3RhbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NzkxMjY5OX0.JSYndaGIZMX7_ScNs5RO4bNlXYHgR-Oii7GWkr1uT4A

###

GET http://127.0.0.1:10001/movies/?director_id=12
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJ1c3RhbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NzkxMjY5OX0.JSYndaGIZMX7_ScNs5RO4bNlXYHgR-Oii7GWkr1uT4A

###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJ1c3RhbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NzkxMjY5OX0.JSYndaGIZMX7_ScNs5RO4bNlXYHgR-Oii7GWkr1uT4A

###

GET http://127.0.0.1:10001/movies/?year=2010
Accept: application/json

###

GET http://127.0.0.1:10001/directors/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJ1c3RhbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NzkxMjY5OX0.JSYndaGIZMX7_ScNs5RO4bNlXYHgR-Oii7GWkr1uT4A

###

GET http://127.0.0.1:10001/directors/1
Accept: application/json

###

GET http://127.0.0.1:10001/users/
Accept: application/json

###

GET http://127.0.0.1:10001/genres/19
Accept: application/json

###

GET http://127.0.0.1:10001/movies/21
Accept: application/json

###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImtvbGEiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzkxMDU2Mn0.8LMXS0RUTSp93LWua5gwLz_gkLiNX_hyI6akNDvYruY


{
  "title": "Проверка авторизации",
  "trailer": "бла бла бла",
  "year": 9999,
  "rating": 54321,
  "description": "12345"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:10001/movies/3
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/movies/21

###

POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "Rustam",
  "password": "Rustam",
  "role": "admin"
}

###

POST http://127.0.0.1:10001/genres/
Accept: application/json
Content-Type: application/json

{
  "name": "test1 genre"
}
###

PUT http://127.0.0.1:10001/genres/19
Accept: application/json
Content-Type: application/json

{
  "name": "test1"
}

###

POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "kola",
  "password": "qwerty",
  "role": "user"
}

###

POST http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "Rustam",
  "password": "Rustam"
}

###

PUT http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlRlc3QxIiwicm9sZSI6IkFkbWluMSIsImV4cCI6MTY2MDMyODg5OX0.QQDDp5zTnoUYKZoznVZbA1uzJJbQDqdX-6heqbYyPkM"

}

###

DELETE http://127.0.0.1:10001/users/9

###